"""empty message

Revision ID: 5f39c51b03da
Revises: e00029325f41
Create Date: 2024-05-02 15:48:33.803063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f39c51b03da'
down_revision = 'e00029325f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('passengers', sa.String(length=250), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_planet_id', sa.Integer(), nullable=True),
    sa.Column('favorite_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('favorite_people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['favorite_planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['favorite_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_planet_id_fkey', type_='foreignkey')
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('people_planet_id_fkey', 'planets', ['planet_id'], ['id'])

    op.drop_table('favorites')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
